#ifndef GAME_BATTLES_MESSAGES_MESSAGE_HPP
#define GAME_BATTLES_MESSAGES_MESSAGE_HPP

#include <cstdint>
#include <string>

namespace game
{
namespace battle
{
/**
 * @brief Represents a message to be displayed. The actual message text is generated by the battle
 * controller
 *
 * @ingroup Battles
 *
 */
class Message {
public:
    /**
     * @brief The type of message to display
     *
     */
    enum struct Type : std::uint8_t {
        _ERROR = 0,
        Attack = 1,
        SuperEffective,
        Callback,
        SendOut,
    };

    /**
     * @brief Construct a new Message
     *
     * @param type The type of message to display
     */
    Message(Type type);

    /**
     * @brief Returns the type of message this is
     *
     */
    Type getType() const;

private:
    const Type type;
    // TODO - other data for message generation
};

} // namespace battle
} // namespace game

#endif
