on:
  repository_dispatch:
    types: [builds]

name: Build Editor Binaries

jobs:
  windows_build:
    name: Windows Build
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Configure Build
        run: cmake -DEDITOR_RELEASE=1 -S . -B ./build

      - name: Build Peoplemon
        run: cd build && cmake --build .

      - name: Download Animation Editor
        run: |
          curl -L -o AnimEditor.zip https://github.com/benreid24/Animation-Editor-2/releases/download/v1.1.3/Windows.zip
          mkdir tools
          Expand-Archive -Path ./AnimEditor.zip -DestinationPath ./tools

      - name: Package Project
        run: |
          mkdir PeoplemonEditor
          mv PeoplemonRelease.exe PeoplemonEditor/PeoplemonDebug.exe
          mv Bundler.exe PeoplemonEditor
          cp lib/BLIB/lib/SFML/extlibs/bin/x64/openal32.dll ./PeoplemonEditor
          
          mv EditorResources PeoplemonEditor
          mv PeoplemonEditorRelease.exe PeoplemonEditor/PeoplemonEditor.exe
          mv tools PeoplemonEditor
          Compress-Archive -Path PeoplemonEditor -DestinationPath WindowsEditor.zip

      - name: Upload Editor Package
        id: upload-release-editor
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.client_payload.release_url }}
          asset_path: ./WindowsEditor.zip
          asset_name: WindowsEditor.zip
          asset_content_type: application/zip
